from dataclasses import dataclass
from datetime import datetime

from backend.base.sqlalchemy._model import Model
from backend.models._users import LicenseUser, User

@dataclass
class Bots(Model):
    Id: int = ...
    display_name: str = ...
    sistema: str = ...
    categoria: str = ...
    configuracao_form: str = ...
    descricao: str = ...
    license_id: int = ...
    license_: LicenseUser = ...
    execucoes: ExecucoesBot = ...

@dataclass
class ExecucoesBot(Model):
    Id: int = ...
    pid: str = ...
    status: str = ...
    data_inicio: datetime = ...
    data_fim: datetime = ...
    user_id: int = ...
    usuario: User = ...
    bot_id: int = ...
    bot: Bots = ...

@dataclass
class CredenciaisRobo(Model):
    Id: int = ...
    nome_credencial: str = ...
    sistema: str = ...
    login_metodo: str = ...
    rastreio: str = ...
    license_id: int = ...
    license_: LicenseUser = ...
