from dataclasses import dataclass

import bcrypt

from backend.extensions import db
from backend.models._bot import Bots, CredenciaisRobo, ExecucoesBot

rel = db.relationship
salt = bcrypt.gensalt()

def _generate_key() -> str: ...

@dataclass
class LicenseUser(db.Model):
    Id: int = ...
    ProductKey: str = ...
    descricao: int = ...
    Nome: str = ...

    CPF: str = ...
    CNPJ: str = ...

    bots: list[Bots] = ...
    usuarios: list[User] = ...
    credenciais: list[CredenciaisRobo] = ...

@dataclass
class User(db.Model):
    Id: int = ...
    login: str = ...
    nome_usuario: str = ...
    email: str = ...
    password: str = ...
    admin: bool = ...

    execucoes: list[ExecucoesBot] = ...

    license_id: int = ...
    license_: LicenseUser = ...

    @classmethod
    def authenticate(cls, username: str, password: str) -> bool: ...
    @property
    def senhacrip(self) -> str: ...
    @senhacrip.setter
    def senhacrip(self, senha_texto: str) -> None: ...
    def check_password(self, senha_texto_claro: str) -> bool: ...
