from typing import NoReturn

from clear import clear
from flask import Flask
from typer import Typer

environ: dict[str, str | None] = ...
FLASK_PORT: int = 5000
clear()

typerapp: Typer = ...

app: Flask = ...

def _api() -> None: ...
def _celery_worker() -> None: ...
def _thread_api() -> NoReturn: ...
def _thread_celery() -> NoReturn: ...
def _start_backend() -> None: ...
