version: '3.9'
services:
  app:
    build:
      context: .
    command: .venv/bin/python -m app

    ports:
      - 8000:8000
  celery:
    build:
        context: .
    command: .venv/bin/python -m celery -A app.__main__.celery worker --loglevel INFO -P eventlet

