version: '3.9'
services:
  app:
    build:
      context: .
    volumes:
      - .:/crawjud_backend
    command: poetry install && poetry run python -m app

    ports:
      - 8000:8000
  celery:
    build:
        context: .
    volumes:
      - .:/crawjud_backend
    command: poetry install && poetry run python -m celery -A app.__main__.celery -E worker -B --loglevel=info -P eventlet

