name: "CrawJUD-Bots"
services:
  # app:
  #   environment:
  #     DOTENV_KEY: "${DOTENV_KEY_PROD:-default_value}"
  #     INTO_DOCKER: "${INTO_DOCKER:-default_value}"
  #   build:
  #     context: "."
  #     dockerfile: ""

  #   volumes:
  #     - ".:C:\\crawjudbot_app"
  #   ports:
  #     - "8000:8000"
  #   hostname: "crawjudbot_app"
  #   command: "python -m app"

  celery:
    environment:
      DOTENV_KEY: "${DOTENV_KEY_PROD:-default_value}"
      INTO_DOCKER: "${INTO_DOCKER:-default_value}"
    build:
      context: "."
    volumes:
      - ".:C:\\crawjudbot_app"
    ports:
      - "3336:3389"
      - "8000:8000"

    hostname: "crawjudbot_app"
    command: " python -m  celery -A app.celery worker -E --loglevel INFO -P threads -c 50"
