version: '3.9'
name: CrawJUD-Bots
services:
  app:
    build:
      context: .
    volumes:
      - .:C:\crawjudbot_app
    ports:
      - 8000:8000
    hostname: crawjudbot_app
    command: python -m app
  celery:
    build:
        context: .
    volumes:
      - .:C:\crawjudbot_app
    hostname: crawjudbot_app
    command: python -m celery -A app.run.celery worker -E --loglevel INFO --autoscale=50,3
