name: "CrawJUD-Bots"
services:
  quart_restapi:
    shm_size: "2gb"
    environment:
      APPLICATION_APP: "quart"
      INTO_DOCKER: "True"
      DOTENV_KEY: "${DOTENV_KEY_PROD:-default_value}"
    build:
      context: "."
    volumes:
      - ".:C:\\crawjudbot_app"
    ports:
      - "8000:8000"

    hostname: "crawjudbot_app"
    command: "python -m app"

  celery_worker:
    shm_size: "2gb"
    environment:
      APPLICATION_APP: "worker"
      DOTENV_KEY: "${DOTENV_KEY_PROD:-default_value}"
      INTO_DOCKER: "True"
    build:
      context: "."
    volumes:
      - ".:C:\\crawjudbot_app"
    ports:
      - "3336:3389"

    hostname: "crawjudbot_app"
    command: "python -m  celery -A app.run.app worker -E --loglevel INFO -P threads -c 50"

  celery_beat:
    shm_size: "2gb"
    environment:
      APPLICATION_APP: "beat"
      DOTENV_KEY: "${DOTENV_KEY_PROD:-default_value}"
      INTO_DOCKER: "${INTO_DOCKER:-default_value}"
    build:
      context: "."
    volumes:
      - ".:C:\\crawjudbot_app"
    hostname: "crawjudbot_app"
    command: "python -m  celery -A app.run.app beat"
