version: '3.9'
services:
  app:
    build:
      context: .
    hostname: crawjudbot_app
    command: .venv/bin/python -m app

    ports:
      - 8000:8000
  celery:
    build:
        context: .

    hostname: crawjudbot_app
    command: .venv/bin/python -m celery -A app.__main__.celery worker -E --loglevel INFO -P gevent

