[project]
name = "crawjud-bots"
version = "0.1.0"
description = ""
authors = [{ name = "Robotz213", email = "nicholas@robotz.dev" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13, <4.0"
dependencies = ["flask (>=3.1.0,<4.0.0)", "flask-mail (>=0.10.0,<0.11.0)", "selenium (>=4.28.1,<5.0.0)", "webdriver-manager (>=4.0.2,<5.0.0)", "google-cloud-storage (>=3.0.0,<4.0.0)", "google-auth (>=2.38.0,<3.0.0)", "openpyxl (>=3.1.5,<4.0.0)", "pypdf (>=5.3.0,<6.0.0)", "tqdm (>=4.67.1,<5.0.0)", "clear (>=2.0.0,<3.0.0)", "bcrypt (>=4.2.1,<5.0.0)", "python-socketio (>=5.12.1,<6.0.0)", "flask-sqlalchemy (>=3.1.1,<4.0.0)", "pywinauto (>=0.6.9,<0.7.0)", "pillow (>=11.1.0,<12.0.0)", "python-docx (>=1.1.2,<2.0.0)", "pymupdf (>=1.25.3,<2.0.0)", "pandas (>=2.2.3,<3.0.0)", "flask-talisman (>=1.1.0,<2.0.0)", "psycopg2 (>=2.9.10,<3.0.0)", "rich (>=13.9.4,<14.0.0)", "deep-translator (>=1.11.4,<2.0.0)", "chrome-version (>=0.3.1,<0.4.0)", "findmyip (>=1.2.0,<2.0.0)", "aiofiles (>=24.1.0,<25.0.0)", "watchdog (>=6.0.0,<7.0.0)", "gitpython (>=3.1.44,<4.0.0)", "pygithub (>=2.5.0,<3.0.0)", "openai (>=1.63.0,<2.0.0)", "redis (>=5.2.1,<6.0.0)", "redis-flask (>=0.0.2,<0.0.3)", "tenacity (>=9.0.0,<10.0.0)", "celery (>=5.4.0,<6.0.0)", "tornado (>=6.4.2,<7.0.0)", "python-dotenv-vault (>=0.6.4,<0.7.0)", "cryptography (<42.0.0)", "python-dotenv (<0.22.0)", "quart (>=0.20.0,<0.21.0)", "uvicorn (>=0.34.0,<0.35.0)", "quart-flask-patch (>=0.3.0,<0.4.0)", "aiohttp (>=3.11.12,<4.0.0)", "pre-commit-html (>=0.1.1,<0.2.0)", "quart-auth (>=0.11.0,<0.12.0)", "aiopath (>=0.7.7,<0.8.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
exclude_dirs = ["tests", ".venv"]

[tool.ruff]
preview = true
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "tests",
    "Lib",
]
extend-include = ["*.ipynb"]
# Same as Black.
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W"]

extend-select = [
    "ANN",
    "ASYNC",
    # "BLE",
    # "FBT",
    "COM",
    # "CPY",
    # "DTZ",
    # "EM",
    "EXE",
    # "FA",
    "ISC",
    "ICN",
    "LOG",
    # "INP",
    "PIE",
    # "UP",
    "PYI",
    "PT",
    "RSE",
    # "RET",
    "SLF",
    "SLOT",
    # "SIM",
    # "TID",
    # "TC",
    "INT",
    # "ARG",
    # "PTH",
    "TD",
    "FIX",
    # "ERA",
    # "PD",
    "PGH",
    # "PL",
    # "TRY",
    # "FLY",
    "NPY",
    # "AIR",
    # "PERF",
    # "FURB",
    # "DOC",
    # "RUF",
]

ignore = ["COM812", "D203", "D211", "D212", "D213"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"


[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.6"
pre-commit = "^4.1.0"
debugpy = "^1.8.12"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pytest-mock = "^3.14.0"
yamllint = "^1.35.1"
pytest-asyncio = "^0.25.3"

