"""Módulo de tratamento de exceptions do robô."""

from .exceptions import (
    AuthenticationError,
    CadastroParteError,
    DriverNotCreatedError,
    ExecutionError,
    FileError,
    FileUploadError,
    GrauIncorretoError,
    LoginSystemError,
    MessageError,
    MessageTokenError,
    MoveNotFoundError,
    NotFoundError,
    PasswordError,
    PasswordTokenError,
    ProcNotFoundError,
    SaveError,
    StartError,
)

__all__ = [
    "AuthenticationError",
    "CadastroParteError",
    "DriverNotCreatedError",
    "ExecutionError",
    "FileError",
    "FileUploadError",
    "GrauIncorretoError",
    "LoginSystemError",
    "MessageError",
    "MessageTokenError",
    "MoveNotFoundError",
    "NotFoundError",
    "PasswordError",
    "PasswordTokenError",
    "ProcNotFoundError",
    "SaveError",
    "StartError",
]
