from typing import Literal, TypedDict

cidades_amazonas = TypedDict(
    "cidades_amazonas",
    {
        "Alvarães": Literal["Interior"],
        "Amaturá": Literal["Interior"],
        "Anamã": Literal["Interior"],
        "Anori": Literal["Interior"],
        "Apuí": Literal["Interior"],
        "Atalaia do Norte": Literal["Interior"],
        "Autazes": Literal["Interior"],
        "Barcelos": Literal["Interior"],
        "Barreirinha": Literal["Interior"],
        "Benjamin Constant": Literal["Interior"],
        "Beruri": Literal["Interior"],
        "Boa Vista do Ramos": Literal["Interior"],
        "Boca do Acre": Literal["Interior"],
        "Borba": Literal["Interior"],
        "Caapiranga": Literal["Interior"],
        "Canutama": Literal["Interior"],
        "Carauari": Literal["Interior"],
        "Careiro": Literal["Interior"],
        "Careiro da Várzea": Literal["Interior"],
        "Coari": Literal["Interior"],
        "Codajás": Literal["Interior"],
        "Eirunepé": Literal["Interior"],
        "Envira": Literal["Interior"],
        "Fonte Boa": Literal["Interior"],
        "Guajará": Literal["Interior"],
        "Humaitá": Literal["Interior"],
        "Ipixuna": Literal["Interior"],
        "Iranduba": Literal["Interior"],
        "Itacoatiara": Literal["Interior"],
        "Itamarati": Literal["Interior"],
        "Itapiranga": Literal["Interior"],
        "Japurá": Literal["Interior"],
        "Juruá": Literal["Interior"],
        "Jutaí": Literal["Interior"],
        "Lábrea": Literal["Interior"],
        "Manacapuru": Literal["Interior"],
        "Manaquiri": Literal["Interior"],
        "Manaus": Literal["Capital"],
        "Manicoré": Literal["Interior"],
        "Maraã": Literal["Interior"],
        "Maués": Literal["Interior"],
        "Nhamundá": Literal["Interior"],
        "Nova Olinda do Norte": Literal["Interior"],
        "Novo Airão": Literal["Interior"],
        "Novo Aripuanã": Literal["Interior"],
        "Parintins": Literal["Interior"],
        "Pauini": Literal["Interior"],
        "Presidente Figueiredo": Literal["Interior"],
        "Rio Preto da Eva": Literal["Interior"],
        "Santa Isabel do Rio Negro": Literal["Interior"],
        "Santo Antônio do Içá": Literal["Interior"],
        "São Gabriel da Cachoeira": Literal["Interior"],
        "São Paulo de Olivença": Literal["Interior"],
        "São Sebastião do Uatumã": Literal["Interior"],
        "Silves": Literal["Interior"],
        "Tabatinga": Literal["Interior"],
        "Tapauá": Literal["Interior"],
        "Tefé": Literal["Interior"],
        "Tonantins": Literal["Interior"],
        "Uarini": Literal["Interior"],
        "Urucará": Literal["Interior"],
        "Urucurituba": Literal["Interior"],
    },
)()
