name: Check Number of Lines Changed

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: cli/setup-gh@v1

      - name: Verificar número de linhas e comentar na PR
        run: |
          LINES_CHANGED=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json additions,deletions --jq '.additions + .deletions')
          MAX_LINES=500

          if [ "$LINES_CHANGED" -gt "$MAX_LINES" ]; then
            MESSAGE="## ❌ Pull Request Too Large

            This PR contains **$LINES_CHANGED lines** changed, exceeding the limit of **$MAX_LINES lines**.

            ### How to fix:
            1. Split this PR into multiple smaller PRs
            2. Remove unnecessary changes
            3. If possible, simplify the changes

            Please adjust the PR to continue with the review process."

            gh pr comment ${{ github.event.pull_request.number }} --body "$MESSAGE"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
